version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
region = "eu-west-2"
stack_name = "di-accounts-prototype"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
